basePath: awesome_project/api/v1
definitions:
  common.ResponseDTO:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  v1.LoginDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8000/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server with oauth.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API Documentation
  version: v1
paths:
  /oauth/login:
    post:
      consumes:
      - application/json
      description: api for logging in by user mail and password
      parameters:
      - description: loginDto object that needs to be added to log in
        in: body
        name: loginDto
        required: true
        schema:
          $ref: '#/definitions/v1.LoginDto'
      - description: grant type
        in: query
        name: grant_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: login by user mail and password
swagger: "2.0"
